# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.1
language: objective-c
xcode_project: VVExtensions.xcodeproj
xcode_scheme: VVExtensions

script:
  - xcodebuild -project VVExtensions.xcodeproj -scheme VVExtensions -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
